apiVersion: v1
kind: Secret
metadata:
  name: external-dns-godaddy
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  GODADDY_API_KEY: <path:secret/data/argocd#godaddy-api-key>
  GODADDY_API_SECRET: <path:secret/data/argocd#godaddy-api-secret>
