apiVersion: v1
kind: Secret
metadata:
  name: jenkins-git
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  username: <path:secret/data/argocd#jenkins-git-username>
  token: <path:secret/data/argocd#jenkins-git-token>
  webhook-token: <path:secret/data/argocd#jenkins-webhook-token>
