apiVersion: v1
kind: Secret
metadata:
  name: jenkins-registry
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: <path:secret/data/argocd#jenkins-registry-dockerconfigjson>
