apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.kibanaHost }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.kibanaHost }}
      secretName: kibana-tls
  rules:
    - host: {{ .Values.kibanaHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.kibanaName }}-kb-http
                port:
                  number: 5601
