apiVersion: v2
name: external-dns
version: 0.1.0
description: external-dns (GoDaddy) for dreamgames-case
dependencies:
  - name: external-dns
    version: 1.21.1
    repository: https://kubernetes-sigs.github.io/external-dns/
