external-dns:
  provider:
    name: godaddy

  sources:
    - service
    - ingress

  domainFilters:
    - myturkishdish.com

  policy: upsert-only
  registry: txt
  txtOwnerId: dreamgames-dev

  env:
    - name: EXTERNAL_DNS_GODADDY_API_KEY
      valueFrom:
        secretKeyRef:
          name: external-dns-godaddy
          key: GODADDY_API_KEY
    - name: EXTERNAL_DNS_GODADDY_API_SECRET
      valueFrom:
        secretKeyRef:
          name: external-dns-godaddy
          key: GODADDY_API_SECRET
